### PR TITLE
Add code coverage reporting via code climate

### PR DESCRIPTION
**Pull request by joshua-rutherford**
This adds a `/coverages` route that returns all code coverage states for the default branch of all repositories.

| Repository ID | Repository Name                        | Lines | Coverage           | 
|---------------|----------------------------------------|-------|--------------------| 
| 85883218      | DecipherNow/gm-dashboard               | 0     | 0                  | 
| 98554869      | DecipherNow/gm-sense                   | 0     | 0                  | 
| 104887689     | DecipherNow/gm-ui-components           | 4419  | 89.47368421052632  | 
| 124289481     | DecipherNow/gm-documentation           | 0     | 0                  | 
| 128966481     | DecipherNow/gm-proxy                   | 0     | 0                  | 
| 129939563     | DecipherNow/gm-xds                     | 0     | 0                  | 
| 130406433     | DecipherNow/gm-slo                     | null  | 91.12709832134293  | 
| 151760159     | DecipherNow/gm-data                    | 16174 | 56.4795918367347   | 
| 157918514     | DecipherNow/gm-jwt-security-gov        | 1231  | 53.03326810176125  | 
| 163761402     | DecipherNow/gm-jwt-security            | 2345  | 24.477244772447722 | 
| 164923639     | DecipherNow/greymatter                 | 0     | 0                  | 
| 166121759     | DecipherNow/gm-catalog                 | 6295  | 81.67330677290838  | 
| 183645685     | DecipherNow/helm-charts                | 0     | 0                  | 
| 184436454     | DecipherNow/gm-control                 | 14405 | 78.43726521412472  | 
| 187048635     | DecipherNow/gm-control-api             | 29402 | 48.89302937308198  | 
| 187049339     | DecipherNow/gm-cli                     | 0     | 0                  | 
| 206618568     | DecipherNow/gm-integrity               | 0     | 0                  | 
| 208092620     | DecipherNow/ansible-playbooks          | 0     | 0                  | 
| 227391946     | DecipherNow/gm-gitbook-sync            | 0     | 0                  | 
| 248583803     | DecipherNow/sense-lad                  | 0     | 0                  | 
| 252290047     | greymatter-io/flux-covidapihub         | 0     | 0                  | 
| 258020588     | greymatter-io/apier                    | 203   | 57.41935483870968  | 
| 278684420     | DecipherNow/sense-autoscaler           | 0     | 0                  | 
| 279394120     | greymatter-io/cli                      | null  | 48.857868020304565 | 
| 282005147     | greymatter-io/buttermilk-sky           | 0     | 0                  | 
| 286791554     | greymatter-io/terraform-greymatter-ecs | 0     | 0                  |

### CODE REVIEW

**Review by kaitmore — APPROVED** [review]
Man, it's almost like you are a VP of engineering with decades of experience or something. LGTM :)

**Comment by kaitmore** [comment]
As an aside, why is the dashboard not reporting coverage here?

**Comment by joshua-rutherford** [comment]
See, I'm not that great.  I researched the `null` ones and was prepared to answer those (it's because they are null) but knew some where zeroed therefore decided not to confirm that all zeros *should* be zeros.

Turns out dashboard is an old soul with a long history and was originally `gm-fabric-dashboard`.  This was still the slug that code climate knew it by so my lookup on the new slug resulted in absolutely nothing.  I've force codeclimate to update it's slug (apparently by changing the repository webhook settings) and now it seems to return data!

**Comment by joshua-rutherford** [comment]
Whereas before that change I got:
```
$ curl -sSLH "Authorization: Token ${CODECLIMATE_TOKEN}" 'https://api.codeclimate.com/v1/repos?github_slug=DecipherNow/gm-dashboard' | jq
{
  "data": []
}
```
after that change I get:
```
$ curl -sSLH "Authorization: Token ${CODECLIMATE_TOKEN}" 'https://api.codeclimate.com/v1/repos?github_slug=DecipherNow/gm-dashboard' | jq
{
  "data": [
    {
      "id": "5a9ea35af6b50b02710092eb",
      "type": "repos",
      "attributes": {
        "analysis_version": 60570,
        "badge_token": "fe44ce8f1f959460fb0f",
        "branch": "release-3.5",
        "created_at": "2018-03-06T14:19:06.477Z",
        "delegated_config_repo_id": "",
        "diff_coverage_enforced": true,
        "diff_coverage_threshold": 50,
        "enable_notifications": true,
        "github_slug": "DecipherNow/gm-dashboard",
        "human_name": "gm-dashboard",
        "last_activity_at": "2020-09-03T23:22:50.315Z",
        "test_reporter_id": "f4edd2fa22298cef102b509ee91b82b931b9e1cc6dd45a561efc4fbf86a34922",
        "total_coverage_enforced": false,
        "vcs_database_id": "85883218",
        "vcs_host": "https://github.com",
        "score": null
      },
      "relationships": {
        "latest_default_branch_snapshot": {
          "data": {
            "id": "5f517a840b9ddc0001001c73",
            "type": "snapshots"
          }
        },
        "latest_default_branch_test_report": {
          "data": {
            "id": "5f4fb875813eeb01a000b5d5",
            "type": "test_reports"
          }
        },
        "account": {
          "data": {
            "id": "5a885af793a3e9027c0008eb",
            "type": "accounts"
          }
        }
      },
      "links": {
        "self": "https://codeclimate.com/repos/5a9ea35af6b50b02710092eb",
        "services": "https://api.codeclimate.com/v1/repos/5a9ea35af6b50b02710092eb/services",
        "web_coverage": "https://codeclimate.com/repos/5a9ea35af6b50b02710092eb/coverage",
        "web_issues": "https://codeclimate.com/repos/5a9ea35af6b50b02710092eb/issues",
        "maintainability_badge": "https://api.codeclimate.com/v1/badges/fe44ce8f1f959460fb0f/maintainability",
        "test_coverage_badge": "https://api.codeclimate.com/v1/badges/fe44ce8f1f959460fb0f/test_coverage"
      },
      "meta": {
        "permissions": {
          "admin": true
        }
      }
    }
  ]
}
```
and
```
$ curl -sSLH "Authorization: Token ${CODECLIMATE_TOKEN}" 'https://api.codeclimate.com/v1/repos/5a9ea35af6b50b02710092eb/test_reports?filter[branch]=release-3.5&page[size]=1' | jq
{
  "data": [
    {
      "id": "5f4fb875813eeb01a000b5d5",
      "type": "test_reports",
      "attributes": {
        "branch": "release-3.5",
        "commit_sha": "1d3f791e14a6aece0deec3f5587720ff0f4da253",
        "committed_at": "2020-09-02T15:18:43.000Z",
        "covered_percent": 75.29411764705883,
        "lines_of_code": 50764,
        "rating": {
          "path": "/",
          "letter": "C",
          "measure": {
            "value": 75.29411764705883,
            "unit": "percent"
          },
          "pillar": "Test Coverage"
        },
        "received_at": "2020-09-02T15:21:25.017Z",
        "state": "done"
      }
    }
  ],
  "links": {
    "self": "https://api.codeclimate.com/v1/repos/5a9ea35af6b50b02710092eb/test_reports?filter%5Bbranch%5D=release-3.5&page%5Bnumber%5D=1&page%5Bsize%5D=1",
    "next": "https://api.codeclimate.com/v1/repos/5a9ea35af6b50b02710092eb/test_reports?filter%5Bbranch%5D=release-3.5&page%5Bnumber%5D=2&page%5Bsize%5D=1",
    "last": "https://api.codeclimate.com/v1/repos/5a9ea35af6b50b02710092eb/test_reports?filter%5Bbranch%5D=release-3.5&page%5Bnumber%5D=14&page%5Bsize%5D=1"
  }
}
```

**Pull request merged**
